### PR TITLE
Fix accidental nulling of pull request in Task.Service

### LINKED ISSUE #1253: Issue syncing to GitHub is trying to change relationship of github_pull_request
https://sentry.io/code-corps/code-corps-api/issues/409216164/

```
Elixir.RuntimeError: you are attempting to change relation :github_pull_request of
CodeCorps.GithubIssue but the `:on_replace` option of
this relation is set to `:raise`.

By default it is not possible to replace or delete embeds and
associations during `cast`. Therefore Ecto requires all existing
data to be given on update. Failing to do so results in this
error message.

If you want to replace data or automatically delete any data
not sent to `cast`, please set the appropriate `:on_replace`
option when defining the relation. The docs for `Ecto.Changeset`
covers the supported options in the "Related data" section.

However, if you don't want to allow data to be replaced or
deleted, only updated, make sure that:

  * If you are attempting to update an existing entry, you
    are including the entry primary key (ID) in the data.

  * If you have a relationship with many children, at least
    the same N children must be given on update.


  File "lib/ecto/changeset/relation.ex", line 201, in Ecto.Changeset.Relation.on_replace/2
  File "lib/ecto/changeset/relation.ex", line 131, in Ecto.Changeset.Relation.change/3
  File "lib/ecto/changeset.ex", line 1049, in Ecto.Changeset.put_change/7
  File "lib/ecto/changeset.ex", line 1136, in Ecto.Changeset.put_relation/5
  File "lib/code_corps/github/sync/issue/github_issue/github_issue.ex", line 40, in CodeCorps.GitHub.Sync.Issue.GithubIssue.create_or_update_issue/3
...
(3 additional frame(s) were not displayed)

(RuntimeError) you are attempting to change relation :github_pull_request of
CodeCorps.GithubIssue but the `:on_replace` option of
this relation is set to `:raise`.

By default it is not possible to replace or delete embeds and
associations during `cast`. Therefore Ecto requires all existing
data to be given on update. Failing to do so results in this
error message.

If you want to replace data or automatically delete any data
not sent to `cast`, please set the appropriate `:on_replace`
option when defining the relation. The docs for `Ecto.Changeset`
covers the supported options in the "Related data" section.

However, if you don't want to allow data to be replaced or
deleted, only updated, make sure that:

  * If you are attempting to update an existing entry, you
    are including the entry primary key (ID) in the data.

  * If you have a relationship with many children, at least
    the same N children must be given on update.
```

### PR DESCRIPTION
**Pull request by joshsmith**
# What's in this PR?

Fixes an issue where we putting a `nil` assoc with `github_pull_request` upon receipt of the payload from GitHub's API.

## References
Fixes #1253

### CODE REVIEW

File: lib/code_corps/task/service.ex [hunk 1]
```diff
@@ -86,10 +86,9 @@ defmodule CodeCorps.Task.Service do
   defp update_on_github(%Task{github_repo_id: _, github_issue_id: nil} = task), do: task |> create_on_github()
   defp update_on_github(%Task{github_repo: github_repo} = task) do
     with {:ok, payload} <- GitHub.API.Issue.update(task),
-         {:ok, %GithubIssue{}} <-
-           payload
-           |> Sync.Issue.GithubIssue.create_or_update_issue(github_repo) do
-      {:ok, Task |> Repo.get(task.id)}
+         {:ok, %GithubIssue{}} <- payload |> Sync.Issue.GithubIssue.create_or_update_issue(github_repo),
+         task <- Task |> Repo.get(task.id) do
```
Comment (asummers) [inline lib/code_corps/task/service.ex]: If this is nil, what happens?

Comment (joshsmith) [reply lib/code_corps/task/service.ex]: Could it be, since the main function expects the `task`?

Comment (joshsmith) [reply lib/code_corps/task/service.ex]: I could move it back out of the `with`, though.

File: test/lib/code_corps/task/service_test.exs [hunk 2]
```diff
@@ -166,6 +168,33 @@ defmodule CodeCorps.Task.ServiceTest do
...
+      task = insert(:task, github_repo: github_repo, github_issue: github_issue)
+
+      {:ok, updated_task} = task |> Task.Service.update(@update_attrs)
+
+      assert_received({:patch, "https://api.github.com/repos/octocat/Hello-World/issues/1347", _body, _headers, _options})
+
+      assert updated_task.id == task.id
+      assert updated_task.title == @update_attrs["title"]
+      assert updated_task.markdown == @update_attrs["markdown"]
+      assert updated_task.body != task.body
```
Comment (asummers) [inline test/lib/code_corps/task/service_test.exs]: Prefer `refute ==` here

File: lib/code_corps/task/service.ex (hunk 1 above)
Comment (asummers) [reply lib/code_corps/task/service.ex]: It's low likelihood but imagine an update and a delete happening in parallel. Could add a `when not(is_nil(task))` guard and handle the nil case in the else.

**Review by asummers — DISMISSED** [review]

**Review by asummers — APPROVED** [review]
