### PR TITLE
Standardize error output for GitHub.Event.Installation

### LINKED ISSUE #1042: Standardize output for CodeCorps.GitHub.Event.Installation
# Problem

Part of #983

All github webhook event handlers should adhere to the same output conventions. 

The `handle` function should `{:ok, any}` where `any` is the relevant output data such as affected records, etc., if the handling process was successful.

Likewise, if the handling process failed, it should result in an `{:erro, atom}` where `atom` is a failure reason.

### PR DESCRIPTION
**Pull request by joshsmith**
# What's in this PR?

Not 100% comfortable with the changes I've made here, so could really use a second set of eyes on this.

## References
Fixes #1042

### CODE REVIEW

File: lib/code_corps/github/event/installation.ex [hunk 1]
```diff
@@ -1,80 +1,103 @@
...
     User
   }
 
-  @typep outcome :: {:ok, GithubAppInstallation.t, Task.t} | {:error, any}
+  alias Ecto.Multi
+
+  @typep outcome :: {:ok, GithubAppInstallation.t} |
+                    {:error, :unexpected_action} |
+                    {:error, :unexpected_payload} |
+                    {:error, any}
```
Comment (joshsmith) [inline lib/code_corps/github/event/installation.ex]: Looks like I missed some error types here.

**Review by begedin — DISMISSED** [review]
Approved your stuff from my end. As for reviewing and approving my stuff, not sure if you'll be able to do that.

Either way, this is ready for another review and hopefully merge.

Note that I've added a new module - `ResultAggregator`, since I've noticed a lot of code repetition in places where we're doing commits on collections of records. This is a sort of attempt to standardize.
